import React, { useState, useRef, useEffect } from 'react';
import { useDropzone } from 'react-dropzone';
import toast from 'react-hot-toast';
import apiService from '../services/api';
import {
  FolderIcon,
  DocumentTextIcon,
  VideoCameraIcon,
  QuestionMarkCircleIcon,
  PhotoIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  EyeIcon,
  ArrowDownTrayIcon,
  TrashIcon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  TagIcon,
  CalendarIcon,
  ClockIcon,
  StarIcon,
  ShareIcon,
  FolderPlusIcon,
  BookOpenIcon,
  AcademicCapIcon,
  BeakerIcon,
  CalculatorIcon,
  GlobeAltIcon,
  PencilIcon,
  PlayIcon,
} from '@heroicons/react/24/outline';
import {
  StarIcon as StarIconSolid,
} from '@heroicons/react/24/solid';

const MyCollection = () => {
  const [selectedSubject, setSelectedSubject] = useState(null);
  const [selectedLesson, setSelectedLesson] = useState(null);
  const [activeTab, setActiveTab] = useState('ai-notes');
  const [searchQuery, setSearchQuery] = useState('');
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [showCreateFolder, setShowCreateFolder] = useState(false);
  const [expandedSubjects, setExpandedSubjects] = useState(['physics']);
  const [newFolderName, setNewFolderName] = useState('');
  const [showAddLesson, setShowAddLesson] = useState(false);
  const [newLessonData, setNewLessonData] = useState({ name: '', description: '', subject: '' });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const fileInputRef = useRef(null);

  // Enhanced data structure matching your requirements
  const [collections, setCollections] = useState({
    physics: {
      name: 'Physics',
      icon: '⚛️',
      color: 'bg-purple-50 border-purple-200',
      lessons: {
        'laws-of-motion': {
          name: 'Laws of Motion',
          description: 'Newton\'s three laws and their applications',
          progress: 75,
          content: {
            'ai-notes': [
              {
                id: 1,
                title: 'Newton\'s First Law Explained',
                dateAdded: '2024-03-20',
                size: '2.5 MB',
                tags: ['newton', 'inertia', 'basics'],
                favorite: true,
                autoGenerated: true,
              },
              {
                id: 2,
                title: 'Force and Acceleration Relationship',
                dateAdded: '2024-03-19',
                size: '1.8 MB',
                tags: ['force', 'acceleration', 'f=ma'],
                favorite: false,
                autoGenerated: true,
              },
            ],
            'user-notes': [
              {
                id: 3,
                title: 'My Class Notes - Laws of Motion',
                dateAdded: '2024-03-18',
                size: '3.2 MB',
                pages: 5,
                tags: ['handwritten', 'class-notes'],
                favorite: true,
                source: 'uploaded',
              },
            ],
            'ai-videos': [
              {
                id: 4,
                title: 'Newton\'s Laws Animation',
                dateAdded: '2024-03-17',
                duration: '8:45',
                thumbnail: 'https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=300',
                tags: ['animation', 'visual-learning'],
                favorite: false,
                views: 12,
              },
            ],
            'important-doubts': [
              {
                id: 5,
                title: 'Why does F=ma work in all cases?',
                dateAdded: '2024-03-16',
                status: 'solved',
                tags: ['conceptual', 'formula'],
                favorite: true,
                answers: 3,
              },
            ],
            'custom-folders': {
              'formulas-only': {
                name: 'Formulas Only',
                items: [
                  {
                    id: 6,
                    title: 'All Newton\'s Law Formulas',
                    type: 'notes',
                    dateAdded: '2024-03-15',
                  },
                ],
              },
              'revision-week-1': {
                name: 'Revision Week 1',
                items: [
                  {
                    id: 7,
                    title: 'Quick Revision Notes',
                    type: 'notes',
                    dateAdded: '2024-03-14',
                  },
                ],
              },
            },
          },
        },
        'thermodynamics': {
          name: 'Thermodynamics',
          description: 'Heat, temperature, and energy transfer',
          progress: 45,
          content: {
            'ai-notes': [],
            'user-notes': [],
            'ai-videos': [],
            'important-doubts': [],
            'custom-folders': {},
          },
        },
      },
    },
    mathematics: {
      name: 'Mathematics',
      icon: '📐',
      color: 'bg-blue-50 border-blue-200',
      lessons: {
        'calculus-basics': {
          name: 'Calculus Basics',
          description: 'Derivatives and integrals fundamentals',
          progress: 60,
          content: {
            'ai-notes': [],
            'user-notes': [],
            'ai-videos': [],
            'important-doubts': [],
            'custom-folders': {},
          },
        },
      },
    },
    chemistry: {
      name: 'Chemistry',
      icon: '🧪',
      color: 'bg-green-50 border-green-200',
      lessons: {
        'organic-chemistry': {
          name: 'Organic Chemistry',
          description: 'Carbon compounds and reactions',
          progress: 30,
          content: {
            'ai-notes': [],
            'user-notes': [],
            'ai-videos': [],
            'important-doubts': [],
            'custom-folders': {},
          },
        },
      },
    },
  });

  const [newItem, setNewItem] = useState({
    title: '',
    type: 'ai-notes',
    subject: '',
    lesson: '',
    customFolder: '',
    tags: [],
    file: null,
  });

  // Fetch collections data from backend
  useEffect(() => {
    const fetchCollections = async () => {
      try {
        setLoading(true);
        console.log('🔄 Fetching collections from API...');
        
        const response = await apiService.getCollections();
        console.log('📡 Collections API Response:', response);
        
        if (response.success) {
          const collectionData = response.data.collection;
          
          // Transform backend data to match frontend structure
          const transformedCollections = {};
          
          if (collectionData.subjects) {
            collectionData.subjects.forEach(subject => {
              transformedCollections[subject.subjectId] = {
                name: subject.subjectName,
                icon: subject.icon,
                color: subject.color,
                lessons: subject.lessons?.reduce((acc, lesson) => {
                  acc[lesson.lessonId] = {
                    name: lesson.lessonName,
                    description: lesson.description || '',
                    progress: lesson.progress || 0,
                    content: lesson.content || {
                      'ai-notes': [],
                      'user-notes': [],
                      'ai-videos': [],
                      'important-doubts': [],
                      'custom-folders': {}
                    }
                  };
                  return acc;
                }, {}) || {}
              };
            });
          }
          
          console.log('✅ Collections data transformed successfully');
          setCollections(transformedCollections);
        } else {
          console.error('❌ API returned error:', response.message);
          setError('Failed to fetch collections');
        }
      } catch (err) {
        console.error('❌ Error fetching collections:', err);
        setError('Error loading collections');
      } finally {
        setLoading(false);
      }
    };

    fetchCollections();
  }, []);

  const contentTabs = [
    { id: 'ai-notes', label: 'AI-Generated Notes', icon: DocumentTextIcon, color: 'text-blue-600' },
    { id: 'user-notes', label: 'My Saved Notes', icon: PencilIcon, color: 'text-green-600' },
    { id: 'ai-videos', label: 'AI Videos', icon: VideoCameraIcon, color: 'text-purple-600' },
    { id: 'important-doubts', label: 'Important Doubts', icon: QuestionMarkCircleIcon, color: 'text-orange-600' },
    { id: 'custom-folders', label: 'Custom Folders', icon: FolderIcon, color: 'text-gray-600' },
  ];

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    accept: {
      'image/*': ['.png', '.jpg', '.jpeg'],
      'application/pdf': ['.pdf'],
      'text/*': ['.txt', '.md'],
    },
    onDrop: (acceptedFiles) => {
      if (acceptedFiles.length > 0) {
        setNewItem({ 
          ...newItem, 
          file: acceptedFiles[0],
          subject: selectedSubject || '',
          lesson: selectedLesson || '',
        });
        setShowSaveModal(true);
      }
    },
  });

  const toggleSubject = (subjectId) => {
    setExpandedSubjects(prev =>
      prev.includes(subjectId)
        ? prev.filter(id => id !== subjectId)
        : [...prev, subjectId]
    );
  };

  const handleSubjectClick = (subjectId) => {
    setSelectedSubject(subjectId);
    setSelectedLesson(null);
    setActiveTab('ai-notes');
  };

  const handleLessonClick = (lessonId) => {
    setSelectedLesson(lessonId);
    setActiveTab('ai-notes');
  };

  const handleCreateCustomFolder = () => {
    if (!newFolderName.trim() || !selectedSubject || !selectedLesson) {
      toast.error('Please enter folder name and select a lesson');
      return;
    }

    const updatedCollections = { ...collections };
    if (!updatedCollections[selectedSubject].lessons[selectedLesson].content['custom-folders']) {
      updatedCollections[selectedSubject].lessons[selectedLesson].content['custom-folders'] = {};
    }

    const folderId = newFolderName.toLowerCase().replace(/\s+/g, '-');
    updatedCollections[selectedSubject].lessons[selectedLesson].content['custom-folders'][folderId] = {
      name: newFolderName,
      items: [],
    };

    setCollections(updatedCollections);
    setNewFolderName('');
    setShowCreateFolder(false);
    toast.success('Custom folder created successfully!');
  };

  const handleAddLesson = async () => {
    if (!newLessonData.name.trim() || !newLessonData.subject) {
      toast.error('Please enter lesson name and select a subject');
      return;
    }

    try {
      // In a real app, this would be an API call
      const updatedCollections = { ...collections };
      const lessonId = `lesson-${Date.now()}`;
      
      updatedCollections[newLessonData.subject].lessons[lessonId] = {
        name: newLessonData.name,
        description: newLessonData.description,
        progress: 0,
        content: {
          'ai-notes': [],
          'user-notes': [],
          'ai-videos': [],
          'important-doubts': [],
          'custom-folders': {}
        }
      };

      setCollections(updatedCollections);
      setNewLessonData({ name: '', description: '', subject: '' });
      setShowAddLesson(false);
      toast.success('Lesson added successfully!');
    } catch (error) {
      toast.error('Failed to add lesson. Please try again.');
    }
  };
  const handleSaveItem = () => {
    if (!newItem.title || !newItem.subject || !newItem.lesson) {
      toast.error('Please fill all required fields');
      return;
    }

    const newItemData = {
      id: Date.now(),
      title: newItem.title,
      dateAdded: new Date().toISOString().split('T')[0],
      tags: newItem.tags,
      favorite: false,
    };

    // Add type-specific properties
    if (newItem.type === 'ai-videos') {
      newItemData.duration = '10:30';
      newItemData.thumbnail = 'https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=300';
      newItemData.views = 0;
    } else if (newItem.type === 'user-notes' || newItem.type === 'ai-notes') {
      newItemData.size = newItem.file ? `${(newItem.file.size / 1024 / 1024).toFixed(1)} MB` : '1.5 MB';
      if (newItem.type === 'user-notes') {
        newItemData.pages = Math.floor(Math.random() * 10) + 1;
        newItemData.source = 'uploaded';
      } else {
        newItemData.autoGenerated = true;
      }
    } else if (newItem.type === 'important-doubts') {
      newItemData.status = 'solved';
      newItemData.answers = Math.floor(Math.random() * 5) + 1;
    }

    // Update collections
    const updatedCollections = { ...collections };
    if (newItem.customFolder && updatedCollections[newItem.subject].lessons[newItem.lesson].content['custom-folders'][newItem.customFolder]) {
      updatedCollections[newItem.subject].lessons[newItem.lesson].content['custom-folders'][newItem.customFolder].items.push({
        ...newItemData,
        type: newItem.type,
      });
    } else {
      updatedCollections[newItem.subject].lessons[newItem.lesson].content[newItem.type].push(newItemData);
    }

    setCollections(updatedCollections);
    setShowSaveModal(false);
    setNewItem({ title: '', type: 'ai-notes', subject: '', lesson: '', customFolder: '', tags: [], file: null });
    toast.success('Item saved successfully!');
  };

  const getContentCount = (subject, lesson, type) => {
    if (!collections[subject]?.lessons[lesson]?.content[type]) return 0;
    if (type === 'custom-folders') {
      return Object.keys(collections[subject].lessons[lesson].content[type]).length;
    }
    return collections[subject].lessons[lesson].content[type].length;
  };

  const getCurrentContent = () => {
    if (!selectedSubject || !selectedLesson) return [];
    
    const lesson = collections[selectedSubject].lessons[selectedLesson];
    if (!lesson) return [];

    if (activeTab === 'custom-folders') {
      return Object.entries(lesson.content['custom-folders'] || {}).map(([id, folder]) => ({
        id,
        ...folder,
        type: 'folder',
      }));
    }

    return lesson.content[activeTab] || [];
  };

  const filteredContent = getCurrentContent().filter(item =>
    item.title?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    item.tags?.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  // Subject Overview Component
  const SubjectOverview = ({ subject }) => {
    const subjectData = collections[subject];
    const lessons = Object.entries(subjectData.lessons);

    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="text-4xl">{subjectData.icon}</div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">{subjectData.name}</h2>
              <p className="text-gray-600">{lessons.length} lessons available</p>
            </div>
          </div>
          <button
            onClick={() => setShowSaveModal(true)}
            className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
          >
            <PlusIcon className="h-5 w-5" />
            <span>Add Content</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {lessons.map(([lessonId, lesson]) => (
            <div
              key={lessonId}
              onClick={() => handleLessonClick(lessonId)}
              className="bg-white rounded-xl p-6 shadow-sm border border-gray-200 hover:shadow-md transition-all duration-200 cursor-pointer hover:scale-105"
            >
              <div className="flex items-center justify-between mb-4">
                <BookOpenIcon className="h-8 w-8 text-indigo-500" />
                <span className="text-sm text-gray-500">{lesson.progress}% complete</span>
              </div>
              
              <h3 className="font-semibold text-gray-900 mb-2">{lesson.name}</h3>
              <p className="text-sm text-gray-600 mb-4">{lesson.description}</p>
              
              <div className="w-full bg-gray-200 rounded-full h-2 mb-4">
                <div
                  className="bg-indigo-600 h-2 rounded-full transition-all duration-300"
                  style={{ width: `${lesson.progress}%` }}
                ></div>
              </div>

              <div className="grid grid-cols-2 gap-4 text-xs text-gray-500">
                <div className="flex items-center space-x-1">
                  <DocumentTextIcon className="h-4 w-4" />
                  <span>{getContentCount(subject, lessonId, 'ai-notes')} AI Notes</span>
                </div>
                <div className="flex items-center space-x-1">
                  <VideoCameraIcon className="h-4 w-4" />
                  <span>{getContentCount(subject, lessonId, 'ai-videos')} Videos</span>
                </div>
                <div className="flex items-center space-x-1">
                  <PencilIcon className="h-4 w-4" />
                  <span>{getContentCount(subject, lessonId, 'user-notes')} Notes</span>
                </div>
                <div className="flex items-center space-x-1">
                  <FolderIcon className="h-4 w-4" />
                  <span>{getContentCount(subject, lessonId, 'custom-folders')} Folders</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  };

  // Lesson Detail Component
  const LessonDetail = ({ subject, lesson }) => {
    const subjectData = collections[subject];
    const lessonData = subjectData.lessons[lesson];

    return (
      <div className="space-y-6">
        {/* Lesson Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <button
              onClick={() => setSelectedLesson(null)}
              className="p-2 hover:bg-gray-100 rounded-full transition-colors duration-200"
            >
              <ChevronRightIcon className="h-6 w-6 text-gray-600 transform rotate-180" />
            </button>
            <div>
              <div className="flex items-center space-x-2 text-sm text-gray-500 mb-1">
                <span>{subjectData.name}</span>
                <ChevronRightIcon className="h-4 w-4" />
                <span>{lessonData.name}</span>
              </div>
              <h2 className="text-2xl font-bold text-gray-900">{lessonData.name}</h2>
              <p className="text-gray-600">{lessonData.description}</p>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <button
              onClick={() => setShowCreateFolder(true)}
              className="flex items-center space-x-2 px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700"
            >
              <FolderPlusIcon className="h-5 w-5" />
              <span>New Folder</span>
            </button>
            <button
              onClick={() => {
                setNewItem({ ...newItem, subject, lesson });
                setShowSaveModal(true);
              }}
              className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
            >
              <PlusIcon className="h-5 w-5" />
              <span>Add Content</span>
            </button>
          </div>
        </div>

        {/* Content Tabs */}
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8">
            {contentTabs.map((tab) => {
              const count = getContentCount(subject, lesson, tab.id);
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center space-x-2 py-4 px-1 border-b-2 font-medium text-sm transition-colors ${
                    activeTab === tab.id
                      ? 'border-indigo-500 text-indigo-600'
                      : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                  }`}
                >
                  <tab.icon className={`h-5 w-5 ${tab.color}`} />
                  <span>{tab.label}</span>
                  <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded-full text-xs">
                    {count}
                  </span>
                </button>
              );
            })}
          </nav>
        </div>

        {/* Search Bar */}
        <div className="relative">
          <MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
          <input
            type="text"
            placeholder={`Search in ${contentTabs.find(t => t.id === activeTab)?.label}...`}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />
        </div>

        {/* Content Grid */}
        {filteredContent.length === 0 ? (
          <div className="text-center py-12">
            <div className="text-6xl mb-4">
              {activeTab === 'ai-notes' ? '📄' : 
               activeTab === 'user-notes' ? '📝' :
               activeTab === 'ai-videos' ? '🎬' :
               activeTab === 'important-doubts' ? '❓' : '🗂️'}
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              No {contentTabs.find(t => t.id === activeTab)?.label} yet
            </h3>
            <p className="text-gray-500 mb-6">
              Start building your collection by adding some content
            </p>
            <button
              onClick={() => {
                setNewItem({ ...newItem, subject, lesson, type: activeTab });
                setShowSaveModal(true);
              }}
              className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
            >
              Add Your First Item
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredContent.map((item) => (
              <div
                key={item.id}
                className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-all duration-200"
              >
                {/* Content Card */}
                {item.type === 'folder' ? (
                  <div className="p-6">
                    <div className="flex items-center space-x-3 mb-4">
                      <FolderIcon className="h-8 w-8 text-blue-500" />
                      <div>
                        <h3 className="font-semibold text-gray-900">{item.name}</h3>
                        <p className="text-sm text-gray-500">{item.items.length} items</p>
                      </div>
                    </div>
                    <div className="flex space-x-2">
                      <button className="flex-1 px-3 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm">
                        Open Folder
                      </button>
                      <button className="p-2 text-red-600 hover:bg-red-50 rounded-lg">
                        <TrashIcon className="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                ) : (
                  <>
                    {/* Thumbnail */}
                    <div className="relative h-40 bg-gray-100">
                      {item.thumbnail ? (
                        <img
                          src={item.thumbnail}
                          alt={item.title}
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center">
                          {activeTab === 'ai-notes' && <DocumentTextIcon className="h-12 w-12 text-blue-400" />}
                          {activeTab === 'user-notes' && <PencilIcon className="h-12 w-12 text-green-400" />}
                          {activeTab === 'ai-videos' && <VideoCameraIcon className="h-12 w-12 text-purple-400" />}
                          {activeTab === 'important-doubts' && <QuestionMarkCircleIcon className="h-12 w-12 text-orange-400" />}
                        </div>
                      )}
                      <button className="absolute top-3 right-3 p-2 bg-white bg-opacity-90 rounded-full hover:bg-opacity-100">
                        {item.favorite ? (
                          <StarIconSolid className="h-4 w-4 text-yellow-500" />
                        ) : (
                          <StarIcon className="h-4 w-4 text-gray-400" />
                        )}
                      </button>
                      {item.duration && (
                        <div className="absolute bottom-3 right-3 bg-black bg-opacity-75 text-white px-2 py-1 rounded text-xs">
                          {item.duration}
                        </div>
                      )}
                    </div>
                    
                    {/* Content */}
                    <div className="p-4">
                      <h3 className="font-semibold text-gray-900 mb-2 line-clamp-2">
                        {item.title}
                      </h3>
                      
                      {/* Metadata */}
                      <div className="flex items-center justify-between text-xs text-gray-500 mb-3">
                        <span>{item.dateAdded}</span>
                        <span>
                          {item.size || item.duration || `${item.pages} pages` || `${item.answers} answers`}
                        </span>
                      </div>
                      
                      {/* Tags */}
                      {item.tags && item.tags.length > 0 && (
                        <div className="flex flex-wrap gap-1 mb-4">
                          {item.tags.slice(0, 2).map((tag, index) => (
                            <span
                              key={index}
                              className="px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded-full"
                            >
                              {tag}
                            </span>
                          ))}
                          {item.tags.length > 2 && (
                            <span className="px-2 py-1 bg-gray-100 text-gray-600 text-xs rounded-full">
                              +{item.tags.length - 2}
                            </span>
                          )}
                        </div>
                      )}
                      
                      {/* Actions */}
                      <div className="flex items-center space-x-2">
                        <button className="flex-1 flex items-center justify-center space-x-2 px-3 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm">
                          {activeTab === 'ai-videos' ? <PlayIcon className="h-4 w-4" /> : <EyeIcon className="h-4 w-4" />}
                          <span>{activeTab === 'ai-videos' ? 'Play' : 'View'}</span>
                        </button>
                        <button className="p-2 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg">
                          <ArrowDownTrayIcon className="h-4 w-4" />
                        </button>
                        <button className="p-2 text-red-600 hover:text-red-700 hover:bg-red-50 rounded-lg">
                          <TrashIcon className="h-4 w-4" />
                        </button>
                      </div>
                    </div>
                  </>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="flex items-center justify-center min-h-96">
          <div className="text-center">
            <div className="animate-spin text-6xl mb-4">📚</div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Loading Collection...</h2>
            <p className="text-gray-600">Fetching your learning materials</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="flex items-center justify-center min-h-96">
          <div className="text-center">
            <div className="text-6xl mb-4">❌</div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Error Loading Collection</h2>
            <p className="text-gray-600 mb-6">{error}</p>
            <button 
              onClick={() => window.location.reload()} 
              className="px-6 py-3 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
            >
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">My Collection</h1>
            <p className="text-gray-600">Your personal learning library - organized by subjects and lessons</p>
            <button
              onClick={() => setShowAddLesson(true)}
              className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              <PlusIcon className="h-5 w-5" />
              <span>Add Lesson</span>
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Sidebar - Subject Navigation */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-xl shadow-sm p-6 sticky top-8">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-semibold text-gray-900">Subjects</h3>
              <span className="text-sm text-gray-500">{Object.keys(collections).length} subjects</span>
            </div>
            
            <div className="space-y-2">
              {Object.entries(collections).map(([subjectId, subject]) => (
                <div key={subjectId}>
                  <button
                    onClick={() => {
                      handleSubjectClick(subjectId);
                      toggleSubject(subjectId);
                    }}
                    className={`w-full flex items-center justify-between p-3 rounded-lg transition-colors ${
                      selectedSubject === subjectId
                        ? 'bg-indigo-50 text-indigo-600 border border-indigo-200'
                        : 'text-gray-700 hover:bg-gray-50'
                    }`}
                  >
                    <div className="flex items-center space-x-3">
                      <span className="text-xl">{subject.icon}</span>
                      <span className="font-medium">{subject.name}</span>
                    </div>
                    {expandedSubjects.includes(subjectId) ? (
                      <ChevronDownIcon className="h-4 w-4 text-gray-500" />
                    ) : (
                      <ChevronRightIcon className="h-4 w-4 text-gray-500" />
                    )}
                  </button>
                  
                  {expandedSubjects.includes(subjectId) && (
                    <div className="ml-6 mt-2 space-y-1">
                      {Object.entries(subject.lessons).map(([lessonId, lesson]) => (
                        <button
                          key={lessonId}
                          onClick={() => {
                            setSelectedSubject(subjectId);
                            handleLessonClick(lessonId);
                          }}
                          className={`w-full text-left p-2 rounded-lg text-sm transition-colors ${
                            selectedLesson === lessonId
                              ? 'bg-indigo-100 text-indigo-700'
                              : 'text-gray-600 hover:bg-gray-50'
                          }`}
                        >
                          📖 {lesson.name}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="lg:col-span-3">
          {/* Drag and Drop Area */}
          <div
            {...getRootProps()}
            className={`mb-6 border-2 border-dashed rounded-xl p-8 text-center transition-colors ${
              isDragActive
                ? 'border-indigo-400 bg-indigo-50'
                : 'border-gray-300 hover:border-gray-400'
            }`}
          >
            <input {...getInputProps()} />
            <PhotoIcon className="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <p className="text-gray-600 mb-2">
              {isDragActive
                ? 'Drop your files here...'
                : 'Drag & drop files here, or click to select'}
            </p>
            <p className="text-sm text-gray-500">
              Auto-saves to current lesson or prompts for organization
            </p>
          </div>

          {/* Content Display */}
          {!selectedSubject ? (
            // Welcome State
            <div className="bg-white rounded-xl shadow-sm p-12 text-center">
              <div className="text-6xl mb-6">📚</div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Welcome to Your Collection</h2>
              <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
                Your personal learning library where all your AI-generated notes, videos, saved materials, 
                and important doubts are organized by subjects and lessons. Select a subject to get started!
              </p>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
                {Object.entries(collections).slice(0, 3).map(([subjectId, subject]) => (
                  <button
                    key={subjectId}
                    onClick={() => handleSubjectClick(subjectId)}
                    className={`${subject.color} p-6 rounded-xl border-2 hover:shadow-md transition-all duration-200 hover:scale-105`}
                  >
                    <div className="text-3xl mb-3">{subject.icon}</div>
                    <h3 className="font-semibold text-gray-900 mb-2">{subject.name}</h3>
                    <p className="text-sm text-gray-600">
                      {Object.keys(subject.lessons).length} lessons
                    </p>
                  </button>
                ))}
              </div>
            </div>
          ) : !selectedLesson ? (
            // Subject Overview
            <SubjectOverview subject={selectedSubject} />
          ) : (
            // Lesson Detail
            <LessonDetail subject={selectedSubject} lesson={selectedLesson} />
          )}
        </div>
      </div>

      {/* Save Item Modal */}
      {showSaveModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="p-6 border-b border-gray-200 flex justify-between items-center">
              <h3 className="text-lg font-semibold">Save to Collection</h3>
              <button
                onClick={() => setShowSaveModal(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                <XMarkIcon className="h-6 w-6" />
              </button>
            </div>
            <div className="p-6 space-y-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Title *
                </label>
                <input
                  type="text"
                  value={newItem.title}
                  onChange={(e) => setNewItem({ ...newItem, title: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="Enter item title"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Content Type *
                </label>
                <select
                  value={newItem.type}
                  onChange={(e) => setNewItem({ ...newItem, type: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                >
                  <option value="ai-notes">AI-Generated Notes</option>
                  <option value="user-notes">My Saved Notes</option>
                  <option value="ai-videos">AI Video</option>
                  <option value="important-doubts">Important Doubt</option>
                </select>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Subject *
                  </label>
                  <select
                    value={newItem.subject}
                    onChange={(e) => setNewItem({ ...newItem, subject: e.target.value, lesson: '' })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  >
                    <option value="">Select Subject</option>
                    {Object.entries(collections).map(([subjectId, subject]) => (
                      <option key={subjectId} value={subjectId}>{subject.name}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Lesson *
                  </label>
                  <select
                    value={newItem.lesson}
                    onChange={(e) => setNewItem({ ...newItem, lesson: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    disabled={!newItem.subject}
                  >
                    <option value="">Select Lesson</option>
                    {newItem.subject && Object.entries(collections[newItem.subject].lessons).map(([lessonId, lesson]) => (
                      <option key={lessonId} value={lessonId}>{lesson.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              {newItem.subject && newItem.lesson && Object.keys(collections[newItem.subject].lessons[newItem.lesson].content['custom-folders'] || {}).length > 0 && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Custom Folder (Optional)
                  </label>
                  <select
                    value={newItem.customFolder}
                    onChange={(e) => setNewItem({ ...newItem, customFolder: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  >
                    <option value="">Save in main section</option>
                    {Object.entries(collections[newItem.subject].lessons[newItem.lesson].content['custom-folders'] || {}).map(([folderId, folder]) => (
                      <option key={folderId} value={folderId}>{folder.name}</option>
                    ))}
                  </select>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Tags (Optional)
                </label>
                <input
                  type="text"
                  placeholder="Enter tags separated by commas"
                  onChange={(e) => setNewItem({ 
                    ...newItem, 
                    tags: e.target.value.split(',').map(tag => tag.trim()).filter(tag => tag) 
                  })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>

              {newItem.file && (
                <div className="bg-gray-50 p-4 rounded-lg">
                  <h4 className="font-medium text-gray-900 mb-2">Selected File</h4>
                  <div className="flex items-center space-x-3">
                    <PhotoIcon className="h-8 w-8 text-gray-400" />
                    <div>
                      <p className="text-sm font-medium text-gray-900">{newItem.file.name}</p>
                      <p className="text-xs text-gray-500">
                        {(newItem.file.size / 1024 / 1024).toFixed(1)} MB
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
            <div className="p-6 border-t border-gray-200 flex justify-end space-x-4">
              <button
                onClick={() => setShowSaveModal(false)}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveItem}
                className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
              >
                Save to Collection
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Create Custom Folder Modal */}
      {showCreateFolder && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl w-full max-w-md">
            <div className="p-6 border-b border-gray-200 flex justify-between items-center">
              <h3 className="text-lg font-semibold">Create Custom Folder</h3>
              <button
                onClick={() => setShowCreateFolder(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                <XMarkIcon className="h-6 w-6" />
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Folder Name *
                </label>
                <input
                  type="text"
                  value={newFolderName}
                  onChange={(e) => setNewFolderName(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="e.g., Formulas Only, Revision Week 1"
                />
              </div>
              {selectedSubject && selectedLesson && (
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-sm text-gray-600">
                    Creating in: <span className="font-medium">
                      {collections[selectedSubject].name} → {collections[selectedSubject].lessons[selectedLesson].name}
                    </span>
                  </p>
                </div>
              )}
            </div>
            <div className="p-6 border-t border-gray-200 flex justify-end space-x-4">
              <button
                onClick={() => setShowCreateFolder(false)}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={handleCreateCustomFolder}
                className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
              >
                Create Folder
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Lesson Modal */}
      {showAddLesson && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl w-full max-w-md">
            <div className="p-6 border-b border-gray-200 flex justify-between items-center">
              <h3 className="text-lg font-semibold">Add New Lesson</h3>
              <button
                onClick={() => setShowAddLesson(false)}
                className="text-gray-500 hover:text-gray-700"
              >
                <XMarkIcon className="h-6 w-6" />
              </button>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Subject *
                </label>
                <select
                  value={newLessonData.subject}
                  onChange={(e) => setNewLessonData({ ...newLessonData, subject: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                >
                  <option value="">Select Subject</option>
                  {Object.entries(collections).map(([subjectId, subject]) => (
                    <option key={subjectId} value={subjectId}>{subject.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Lesson Name *
                </label>
                <input
                  type="text"
                  value={newLessonData.name}
                  onChange={(e) => setNewLessonData({ ...newLessonData, name: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="e.g., Introduction to Calculus"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Description (Optional)
                </label>
                <textarea
                  value={newLessonData.description}
                  onChange={(e) => setNewLessonData({ ...newLessonData, description: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  placeholder="Brief description of the lesson"
                  rows="3"
                />
              </div>
            </div>
            <div className="p-6 border-t border-gray-200 flex justify-end space-x-4">
              <button
                onClick={() => setShowAddLesson(false)}
                className="px-4 py-2 text-gray-600 hover:text-gray-800"
              >
                Cancel
              </button>
              <button
                onClick={handleAddLesson}
                className="px-6 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
              >
                Add Lesson
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MyCollection;